name: Springboot CI on Push

on:
  push:
    branches: [ "develop" ]
  # for debug
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./springboot

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Build & Test
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Test with Gradle
      run: ./gradlew test

    # Setup SSH
    - name: Set up SSH agent with private key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SPRINGBOOT_EC2_SSH_KEY }}
    - name: Add remote server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SPRINGBOOT_HOST_DNS }} >> ~/.ssh/known_hosts

    # Deploy
    - name: SCP jar file to server
      run: |
        scp *jar ${{ secrets.SPRINGBOOT_USERNAME }}@${{ secrets.SPRINGBOOT_HOST_DNS }}:\
        ${{ secrets.SPRINGBOOT_TARGET_DIR }}
      working-directory: ./springboot/build/libs
    - name: Execute remote commands
      run: |
        ssh -v ${{ secrets.SPRINGBOOT_USERNAME }}@${{ secrets.SPRINGBOOT_HOST_DNS }} \
        "fuser -k 8080/tcp || true"
        ssh -v ${{ secrets.SPRINGBOOT_USERNAME }}@${{ secrets.SPRINGBOOT_HOST_DNS }} \
        "sudo nohup /usr/bin/java -jar ${{ secrets.SPRINGBOOT_TARGET_DIR }}/*.jar\
         > {{ secrets.SPRINGBOOT_TARGET_DIR }}/app.log 2>&1 &"
